resources:
    App\Entity\Category:
        class: App\Entity\Category
        operations:
            ApiPlatform\Metadata\GetCollection:
                filters: ['app.api_platform.filter.category.order']
                security: "is_granted('ROLE_USER')"
            ApiPlatform\Metadata\Get:
                security: "is_granted('ROLE_USER')"
            ApiPlatform\Metadata\Post:
                security: "is_granted('ROLE_ADMIN')"
            ApiPlatform\Metadata\Patch:
                security: "is_granted('ROLE_ADMIN')"
            ApiPlatform\Metadata\Delete:
                security: "is_granted('ROLE_ADMIN')"
        paginationEnabled: true
        normalizationContext:
            groups: ['category:read']
        denormalizationContext:
            groups: ['category:write']
properties:
    App\Entity\Category:
        products:
            readableLink: false
            writableLink: false
